// Cloudflare Pages middleware: Markdown content negotiation.
//
// Self-hosted equivalent of Cloudflare's "Markdown for Agents" zone feature
// (which is gated to Pro+ plans). On any request whose `Accept` header
// includes `text/markdown`, this rewrites to the matching pre-built `.md`
// sidecar generated by astro-llms-md and serves it with
//   Content-Type: text/markdown; charset=utf-8
//   x-markdown-tokens: <integer>
//
// URL → file mapping (matches astro-llms-md output):
//   /                        → /index.md   (renamed from .md by fix-llms-md.mjs)
//   /components/modal        → /components/modal.md
//   /components/modal/dev    → /components/modal/dev.md
//   /search                  → /search.md
//
// Requests for paths that already resolve to a non-HTML asset (JSON, XML,
// markdown, plain-text, Pagefind, Astro bundles, etc.) fall through
// unchanged. Browsers without the Accept header receive the normal HTML.

type PagesContext = {
  request: Request;
  next: (input?: Request | string) => Promise<Response>;
};

const SKIP_PREFIXES = ['/api/', '/.well-known/', '/pagefind/', '/_astro/', '/brand/'];
const SKIP_EXACT = new Set([
  '/robots.txt',
  '/sitemap-index.xml',
  '/llms.txt',
  '/llms-full.txt',
  '/favicon.svg',
  '/mcp',
]);

function shouldSkip(pathname: string): boolean {
  if (SKIP_EXACT.has(pathname)) return true;
  if (SKIP_PREFIXES.some((p) => pathname.startsWith(p))) return true;
  if (pathname.startsWith('/sitemap-') && pathname.endsWith('.xml')) return true;
  // any path with a non-html-ish file extension
  const lastSlash = pathname.lastIndexOf('/');
  const tail = pathname.slice(lastSlash + 1);
  if (tail.includes('.') && !tail.endsWith('.html')) return true;
  return false;
}

function mdPathFor(pathname: string): string {
  if (pathname === '/' || pathname === '') return '/index.md';
  const trimmed = pathname.endsWith('/') ? pathname.slice(0, -1) : pathname;
  return `${trimmed}.md`;
}

// 4 chars/token is Cloudflare's documented heuristic for x-markdown-tokens
// when an exact LLM tokenizer isn't available at the edge.
function estimateTokens(body: string): number {
  return Math.ceil(body.length / 4);
}

export const onRequest = async ({ request, next }: PagesContext): Promise<Response> => {
  if (request.method !== 'GET' && request.method !== 'HEAD') return next();

  const accept = request.headers.get('accept') ?? '';
  if (!accept.toLowerCase().includes('text/markdown')) return next();

  const url = new URL(request.url);
  if (shouldSkip(url.pathname)) return next();

  const mdUrl = new URL(mdPathFor(url.pathname), url);
  const mdRequest = new Request(mdUrl.toString(), {
    method: 'GET',
    headers: request.headers,
  });
  const mdResponse = await next(mdRequest);

  // Cloudflare Pages serves index.html as 200 for any path that doesn't match
  // a real asset, so a successful response is not enough. Verify the resolved
  // asset actually has a markdown content type before treating it as the .md
  // sidecar — otherwise fall through to whatever the original URL would serve.
  const resolvedType = mdResponse.headers.get('content-type') ?? '';
  if (!mdResponse.ok || !resolvedType.toLowerCase().startsWith('text/markdown')) {
    return next();
  }

  const body = await mdResponse.text();
  const headers = new Headers({
    'Content-Type': 'text/markdown; charset=utf-8',
    'x-markdown-tokens': String(estimateTokens(body)),
    'Cache-Control': 'public, max-age=300, must-revalidate',
    Vary: 'Accept',
  });

  return new Response(request.method === 'HEAD' ? null : body, {
    status: 200,
    headers,
  });
};
