// Cloudflare Worker entry — replaces the previous Cloudflare Pages
// `functions/` directory.
//
// Two responsibilities:
// 1. /mcp — Streamable-HTTP transport for the @uianatomy/mcp-server. The
//    component bundle is loaded from JSON at module init so the handler
//    stays cold-start-cheap and FS-free (Workers runtime has no FS).
// 2. Markdown content negotiation — on Accept: text/markdown, swap the
//    request URL for the matching .md sidecar generated by astro-llms-md
//    and respond with Content-Type: text/markdown + x-markdown-tokens.
//
// Everything else falls through to env.ASSETS for static-asset serving.

import { WebStandardStreamableHTTPServerTransport } from '@modelcontextprotocol/sdk/server/webStandardStreamableHttp.js';
import { createServer } from '../mcp-server/src/server.js';
import {
  setAbout,
  setComponents,
  setImplementations,
  setPatterns,
  setSubAnatomies,
} from '../mcp-server/src/state.js';
import {
  loadAboutFromBundle,
  loadComponentsFromBundle,
  loadImplementationsFromBundle,
  loadPatternsFromBundle,
  loadSubAnatomiesFromBundle,
} from '@uianatomy/shared/bundle';
import bundleJson from '@uianatomy/shared/content-bundle.json';
import implBundleJson from '@uianatomy/shared/implementations-bundle.json';
import patternsBundleJson from '@uianatomy/shared/patterns-bundle.json';
import subAnatomiesBundleJson from '@uianatomy/shared/sub-anatomies-bundle.json';
import aboutBundleJson from '@uianatomy/shared/about-bundle.json';

// P6-126 / ADR-030 — content-bundle is pre-resolved at bundle-write time
// (sub-anatomy `$ref` entries flattened into anatomy[]) so the worker
// does not need a sub-anatomies map to load components. The sub-anatomies
// bundle is registered separately so MCP tools (list_sub_anatomies,
// get_sub_anatomy, get_canonical_vocabularies.subAnatomies) can serve it.
setSubAnatomies(loadSubAnatomiesFromBundle(subAnatomiesBundleJson as Record<string, unknown>));
setComponents(loadComponentsFromBundle(bundleJson as Record<string, unknown>));
setImplementations(
  loadImplementationsFromBundle(implBundleJson as Record<string, Record<string, unknown>>),
);
setPatterns(loadPatternsFromBundle(patternsBundleJson as Record<string, unknown>));
setAbout(loadAboutFromBundle(aboutBundleJson as { markdown: unknown; summary: unknown }));

interface Env {
  ASSETS: { fetch: (request: Request) => Promise<Response> };
  // P6-206 / ADR-037 — counts-only MCP telemetry. Optional: absent in
  // environments where the binding isn't provisioned (e.g. a preview
  // deploy before the dataset exists); recordToolCall() no-ops in that case.
  MCP_ANALYTICS?: AnalyticsEngineDataset;
}

// P6-206 / ADR-037 — one data point per tools/call request: tool name +
// best-effort subject id, nothing else (no arguments, no client identifiers).
// Analytics Engine timestamps every write automatically. Fire-and-forget: a
// telemetry failure must never affect the actual MCP response.
function extractToolCall(body: unknown): { toolName: string; subjectId: string | undefined } | null {
  if (typeof body !== 'object' || body === null) return null;
  const rpc = body as { method?: unknown; params?: unknown };
  if (rpc.method !== 'tools/call') return null;
  const params = rpc.params as { name?: unknown; arguments?: unknown } | undefined;
  if (typeof params?.name !== 'string') return null;
  const args = params.arguments as Record<string, unknown> | undefined;
  const subjectId =
    (typeof args?.id === 'string' && args.id) ||
    (typeof args?.componentId === 'string' && args.componentId) ||
    (Array.isArray(args?.ids) && typeof args.ids[0] === 'string' && args.ids[0]) ||
    undefined;
  return { toolName: params.name, subjectId };
}

function recordToolCall(env: Env, toolName: string, subjectId: string | undefined): void {
  try {
    env.MCP_ANALYTICS?.writeDataPoint({
      blobs: [toolName, subjectId ?? ''],
      indexes: [toolName],
    });
  } catch {
    // Never let telemetry break the MCP response.
  }
}

const SKIP_PREFIXES = ['/api/', '/.well-known/', '/pagefind/', '/_astro/', '/brand/'];
const SKIP_EXACT = new Set([
  '/robots.txt',
  '/sitemap-index.xml',
  '/llms.txt',
  '/llms-full.txt',
  '/favicon.svg',
  '/mcp',
]);

function shouldSkipMd(pathname: string): boolean {
  if (SKIP_EXACT.has(pathname)) return true;
  if (SKIP_PREFIXES.some((p) => pathname.startsWith(p))) return true;
  if (pathname.startsWith('/sitemap-') && pathname.endsWith('.xml')) return true;
  const lastSlash = pathname.lastIndexOf('/');
  const tail = pathname.slice(lastSlash + 1);
  if (tail.includes('.') && !tail.endsWith('.html')) return true;
  return false;
}

function mdPathFor(pathname: string): string {
  if (pathname === '/' || pathname === '') return '/index.md';
  const trimmed = pathname.endsWith('/') ? pathname.slice(0, -1) : pathname;
  return `${trimmed}.md`;
}

// 4 chars/token is Cloudflare's documented heuristic for x-markdown-tokens
// when an exact LLM tokenizer isn't available at the edge.
function estimateTokens(body: string): number {
  return Math.ceil(body.length / 4);
}

async function handleMcp(request: Request, env: Env): Promise<Response> {
  if (request.method !== 'POST' && request.method !== 'GET') {
    return new Response('Method Not Allowed', {
      status: 405,
      headers: { Allow: 'POST, GET' },
    });
  }
  // P6-206 / ADR-037 — peek the body for tools/call telemetry via a clone,
  // so the original request stream is untouched for the transport below.
  if (request.method === 'POST') {
    try {
      const parsed: unknown = await request.clone().json();
      const call = extractToolCall(parsed);
      if (call) recordToolCall(env, call.toolName, call.subjectId);
    } catch {
      // Not JSON, or not a tools/call shape — nothing to record.
    }
  }
  const transport = new WebStandardStreamableHTTPServerTransport();
  const server = createServer();
  await server.connect(transport);
  return transport.handleRequest(request);
}

async function maybeMarkdown(request: Request, env: Env): Promise<Response | null> {
  if (request.method !== 'GET' && request.method !== 'HEAD') return null;

  const accept = request.headers.get('accept') ?? '';
  if (!accept.toLowerCase().includes('text/markdown')) return null;

  const url = new URL(request.url);
  if (shouldSkipMd(url.pathname)) return null;

  const mdUrl = new URL(mdPathFor(url.pathname), url);
  const mdRequest = new Request(mdUrl.toString(), {
    method: 'GET',
    headers: request.headers,
  });
  const mdResponse = await env.ASSETS.fetch(mdRequest);

  // Workers Static Assets returns a 404-page response for unmatched paths
  // when not_found_handling is "404-page" — verify the resolved asset is
  // actually markdown before treating it as the .md sidecar.
  const resolvedType = mdResponse.headers.get('content-type') ?? '';
  if (!mdResponse.ok || !resolvedType.toLowerCase().startsWith('text/markdown')) {
    return null;
  }

  const body = await mdResponse.text();
  return new Response(request.method === 'HEAD' ? null : body, {
    status: 200,
    headers: {
      'Content-Type': 'text/markdown; charset=utf-8',
      'x-markdown-tokens': String(estimateTokens(body)),
      'Cache-Control': 'public, max-age=300, must-revalidate',
      Vary: 'Accept',
    },
  });
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === '/mcp') {
      return handleMcp(request, env);
    }

    const md = await maybeMarkdown(request, env);
    if (md) return md;

    return env.ASSETS.fetch(request);
  },
};
